/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  BytesLike,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { InitializedProxy } from "../InitializedProxy";

export class InitializedProxy__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _logic: string,
    _initializationCalldata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<InitializedProxy> {
    return super.deploy(
      _logic,
      _initializationCalldata,
      overrides || {}
    ) as Promise<InitializedProxy>;
  }
  getDeployTransaction(
    _logic: string,
    _initializationCalldata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _logic,
      _initializationCalldata,
      overrides || {}
    );
  }
  attach(address: string): InitializedProxy {
    return super.attach(address) as InitializedProxy;
  }
  connect(signer: Signer): InitializedProxy__factory {
    return super.connect(signer) as InitializedProxy__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitializedProxy {
    return new Contract(address, _abi, signerOrProvider) as InitializedProxy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_logic",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_initializationCalldata",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "logic",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161034538038061034583398101604081905261002f916100d7565b6001600160601b0319606083901b1660805260405160009081906001600160a01b0385169061005f9085906101a0565b600060405180830381855af49150503d806000811461009a576040519150601f19603f3d011682016040523d82523d6000602084013e61009f565b606091505b50915091508181906100cd5760405162461bcd60e51b81526004016100c491906101bc565b60405180910390fd5b5050505050610235565b600080604083850312156100e9578182fd5b82516001600160a01b03811681146100ff578283fd5b60208401519092506001600160401b038082111561011b578283fd5b818501915085601f83011261012e578283fd5b8151818111156101405761014061021f565b604051601f8201601f19908116603f011681019083821181831017156101685761016861021f565b81604052828152886020848701011115610180578586fd5b6101918360208301602088016101ef565b80955050505050509250929050565b600082516101b28184602087016101ef565b9190910192915050565b60208152600082518060208401526101db8160408501602087016101ef565b601f01601f19169190910160400192915050565b60005b8381101561020a5781810151838201526020016101f2565b83811115610219576000848401525b50505050565b634e487b7160e01b600052604160045260246000fd5b60805160601c60ef61025660003960008181602a0152607b015260ef6000f3fe608060405260043610601f5760003560e01c8063d7dfa0dd14606b576025565b36602557005b6040517f00000000000000000000000000000000000000000000000000000000000000009036600082376000803683855af43d806000843e8180156067578184f35b8184fd5b348015607657600080fd5b50609d7f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220c7f21ae2d0aa6165c1d6b5b731adfd2d9298cf5bcd54f8a0f5e40a5d6454079864736f6c63430008040033";
