/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { MulticallUpgradeable } from "../MulticallUpgradeable";

export class MulticallUpgradeable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MulticallUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MulticallUpgradeable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
