/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DankBankMarketDataInterface extends ethers.utils.Interface {
  functions: {
    "ethPoolSupply(address)": FunctionFragment;
    "virtualEthPoolSupply(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ethPoolSupply",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "virtualEthPoolSupply",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "ethPoolSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "virtualEthPoolSupply",
    data: BytesLike
  ): Result;

  events: {
    "DankBankBuy(address,address,uint256,uint256)": EventFragment;
    "DankBankSell(address,address,uint256,uint256)": EventFragment;
    "LiquidityAdded(address,address,uint256,uint256)": EventFragment;
    "LiquidityRemoved(address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DankBankBuy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DankBankSell"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidityAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidityRemoved"): EventFragment;
}

export class DankBankMarketData extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DankBankMarketDataInterface;

  functions: {
    ethPoolSupply(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "ethPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    virtualEthPoolSupply(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "virtualEthPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  ethPoolSupply(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "ethPoolSupply(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  virtualEthPoolSupply(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "virtualEthPoolSupply(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    ethPoolSupply(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "ethPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    virtualEthPoolSupply(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "virtualEthPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    DankBankBuy(
      buyer: string | null,
      token: null,
      investmentAmount: null,
      tokensBought: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        buyer: string;
        token: string;
        investmentAmount: BigNumber;
        tokensBought: BigNumber;
      }
    >;

    DankBankSell(
      seller: string | null,
      token: null,
      returnAmount: null,
      tokensSold: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        seller: string;
        token: string;
        returnAmount: BigNumber;
        tokensSold: BigNumber;
      }
    >;

    LiquidityAdded(
      funder: string | null,
      token: null,
      amountAdded: null,
      sharesMinted: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        funder: string;
        token: string;
        amountAdded: BigNumber;
        sharesMinted: BigNumber;
      }
    >;

    LiquidityRemoved(
      funder: string | null,
      token: null,
      tokensRemoved: null,
      ethRemoved: null,
      sharesBurnt: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        funder: string;
        token: string;
        tokensRemoved: BigNumber;
        ethRemoved: BigNumber;
        sharesBurnt: BigNumber;
      }
    >;
  };

  estimateGas: {
    ethPoolSupply(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "ethPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    virtualEthPoolSupply(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "virtualEthPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ethPoolSupply(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ethPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    virtualEthPoolSupply(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "virtualEthPoolSupply(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
